print("This is statement")
print('this is statement 2')
print("add 2 +2 ",2+2)
print("sub 10 from 2",10-2)
print("divide 10 by 2",10/2)
print("statement 6")
print("multiply",2*2)
print("this is fl",2.2)
print("this is string")
print("this is char",'A')
print("please don't be late for class")